default: &default
  pool: 5
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: silver
  password: li2oeeaj

development:
  <<: *default
  database: bitshares_faucet

staging:
  <<: *default
  database: bitshares_faucet_staging

test:
  <<: *default
  database: bitshares_faucet_test

production:
  <<: *default
  database: bitshares_faucet
